FROM ubuntu
RUN apt-get update && apt-get install curl -y

ARG host  
RUN TOKEN=$(curl http://$host:8080/v1/secrets/file/id_rsa) && echo 'ENV:' && env && echo 'TOKEN ENV' && echo $TOKEN && unset $TOKEN
RUN curl -O ~/.ssh/id_rsa http://$host:8080/v1/secrets/file/id_rsa && ssh -T git@github.com && rm ~/.ssh/id_rsa  
